---
version: '3.4'
services:
  redis:
    image: redis:6.2.6
    volumes:
      - "./data/redis:/data"
    ports:
      - 6379:6379
  db:
    image: mysql:8.0.29-oracle
    restart: always
    environment:
      - MYSQL_DATABASE=wxgpt
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080